//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.ComponentModel.Design;
using System.Xml.Serialization;

namespace pansiyonkayit_otomasyonu
{
    [DesignerCategory("code"), HelpKeyword("vs.data.DataSet"), Serializable, ToolboxItem(true), XmlRoot("ymgDataSet"), XmlSchemaProvider("GetTypedDataSetSchema")]
    public class ymgDataSetBase
    {
    }
}