//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace pansiyonkayit_otomasyonu { }


    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    //[global::System.Serializable()]
    //[global::System.ComponentModel.DesignerCategoryAttribute("code")]
    //[global::System.ComponentModel.ToolboxItem(true)]
    //[global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    //[global::System.Xml.Serialization.XmlRootAttribute("ymgDataSet")]
    //[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    //public partial class ymgDataSet : global::System.Data.DataSet {

        //private Table_1DataTable tableTable_1;

        // private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;

       // [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
       // [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")] 
        /*public ymgDataSet() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }*/

//[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
//[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
/*protected ymgDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
        base(info, context, false) {
    if ((this.IsBinarySerialized(info, context) == true)) {
        this.InitVars(false);
        global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
        this.Tables.CollectionChanged += schemaChangedHandler1;
        this.Relations.CollectionChanged += schemaChangedHandler1;
        return;
    }
    string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
    if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
        global::System.Data.DataSet ds = new global::System.Data.DataSet();
        ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
        if ((ds.Tables["Table_1"] != null)) {
            base.Tables.Add(new Table_1DataTable(ds.Tables["Table_1"]));
        }
        this.DataSetName = ds.DataSetName;
        this.Prefix = ds.Prefix;
        this.Namespace = ds.Namespace;
        this.Locale = ds.Locale;
        this.CaseSensitive = ds.CaseSensitive;
        this.EnforceConstraints = ds.EnforceConstraints;
        this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
        this.InitVars();
    }
    else {
        this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
    }
    this.GetSerializationData(info, context);
    global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
    base.Tables.CollectionChanged += schemaChangedHandler;
    this.Relations.CollectionChanged += schemaChangedHandler;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Browsable(false)]
[global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
public Table_1DataTable Table_1 {
    get {
        return this.tableTable_1;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.BrowsableAttribute(true)]
[global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
    get {
        return this._schemaSerializationMode;
    }
    set {
        this._schemaSerializationMode = value;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
public new global::System.Data.DataTableCollection Tables {
    get {
        return base.Tables;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
public new global::System.Data.DataRelationCollection Relations {
    get {
        return base.Relations;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected override void InitializeDerivedDataSet() {
    this.BeginInit();
    this.InitClass();
    this.EndInit();
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public override global::System.Data.DataSet Clone() {
    ymgDataSet cln = ((ymgDataSet)(base.Clone()));
    cln.InitVars();
    cln.SchemaSerializationMode = this.SchemaSerializationMode;
    return cln;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected override bool ShouldSerializeTables() {
    return false;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected override bool ShouldSerializeRelations() {
    return false;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
    if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
        this.Reset();
        global::System.Data.DataSet ds = new global::System.Data.DataSet();
        ds.ReadXml(reader);
        if ((ds.Tables["Table_1"] != null)) {
            base.Tables.Add(new Table_1DataTable(ds.Tables["Table_1"]));
        }
        this.DataSetName = ds.DataSetName;
        this.Prefix = ds.Prefix;
        this.Namespace = ds.Namespace;
        this.Locale = ds.Locale;
        this.CaseSensitive = ds.CaseSensitive;
        this.EnforceConstraints = ds.EnforceConstraints;
        this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
        this.InitVars();
    }
    else {
        this.ReadXml(reader);
        this.InitVars();
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
    global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
    this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
    stream.Position = 0;
    return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
internal void InitVars() {
    this.InitVars(true);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
internal void InitVars(bool initTable) {
    this.tableTable_1 = ((Table_1DataTable)(base.Tables["Table_1"]));
    if ((initTable == true)) {
        if ((this.tableTable_1 != null)) {
            this.tableTable_1.InitVars();
        }
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private void InitClass() {
    this.DataSetName = "ymgDataSet";
    this.Prefix = "";
    this.Namespace = "http://tempuri.org/ymgDataSet1.xsd";
    this.EnforceConstraints = true;
    this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
    this.tableTable_1 = new Table_1DataTable();
    base.Tables.Add(this.tableTable_1);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private bool ShouldSerializeTable_1() {
    return false;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
    if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
        this.InitVars();
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
    ymgDataSet ds = new ymgDataSet();
    global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
    global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
    global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
    any.Namespace = ds.Namespace;
    sequence.Items.Add(any);
    type.Particle = sequence;
    global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
    if (xs.Contains(dsSchema.TargetNamespace)) {
        global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
        global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
        try {
            global::System.Xml.Schema.XmlSchema schema = null;
            dsSchema.Write(s1);
            for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                s2.SetLength(0);
                schema.Write(s2);
                if ((s1.Length == s2.Length)) {
                    s1.Position = 0;
                    s2.Position = 0;
                    for (; ((s1.Position != s1.Length) 
                                && (s1.ReadByte() == s2.ReadByte())); ) {
                        ;
                    }
                    if ((s1.Position == s1.Length)) {
                        return type;
                    }
                }
            }
        }
        finally {
            if ((s1 != null)) {
                s1.Close();
            }
            if ((s2 != null)) {
                s2.Close();
            }
        }
    }
    xs.Add(dsSchema);
    return type;
}

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public delegate void Table_1RowChangeEventHandler(object sender, Table_1RowChangeEvent e);

/// <summary>
///Represents the strongly named DataTable class.
///</summary>
[global::System.Serializable()]
[global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
public partial class Table_1DataTable : global::System.Data.TypedTableBase<Table_1Row> {

    private global::System.Data.DataColumn columnMusteriID;

    private global::System.Data.DataColumn columnAdSoyad;

    private global::System.Data.DataColumn columnTC;

    private global::System.Data.DataColumn columnMail;

    private global::System.Data.DataColumn columnTelNo;

    private global::System.Data.DataColumn columnGirisTarihi;

    private global::System.Data.DataColumn columnCıkısTarihi;

    private global::System.Data.DataColumn columnUcret;

    private global::System.Data.DataColumn columnOdaNo;

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public Table_1DataTable() {
        this.TableName = "Table_1";
        this.BeginInit();
        this.InitClass();
        this.EndInit();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    internal Table_1DataTable(global::System.Data.DataTable table) {
        this.TableName = table.TableName;
        if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
            this.CaseSensitive = table.CaseSensitive;
        }
        if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
            this.Locale = table.Locale;
        }
        if ((table.Namespace != table.DataSet.Namespace)) {
            this.Namespace = table.Namespace;
        }
        this.Prefix = table.Prefix;
        this.MinimumCapacity = table.MinimumCapacity;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected Table_1DataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
            base(info, context) {
        this.InitVars();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn MusteriIDColumn {
        get {
            return this.columnMusteriID;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn AdSoyadColumn {
        get {
            return this.columnAdSoyad;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn TCColumn {
        get {
            return this.columnTC;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn MailColumn {
        get {
            return this.columnMail;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn TelNoColumn {
        get {
            return this.columnTelNo;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn GirisTarihiColumn {
        get {
            return this.columnGirisTarihi;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn CıkısTarihiColumn {
        get {
            return this.columnCıkısTarihi;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn UcretColumn {
        get {
            return this.columnUcret;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataColumn OdaNoColumn {
        get {
            return this.columnOdaNo;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    [global::System.ComponentModel.Browsable(false)]
    public int Count {
        get {
            return this.Rows.Count;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public Table_1Row this[int index] {
        get {
            return ((Table_1Row)(this.Rows[index]));
        }
    }

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public event Table_1RowChangeEventHandler Table_1RowChanging;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public event Table_1RowChangeEventHandler Table_1RowChanged;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public event Table_1RowChangeEventHandler Table_1RowDeleting;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public event Table_1RowChangeEventHandler Table_1RowDeleted;

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public void AddTable_1Row(Table_1Row row) {
        this.Rows.Add(row);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public Table_1Row AddTable_1Row(string AdSoyad, int TC, string Mail, int TelNo, System.DateTime GirisTarihi, System.DateTime CıkısTarihi, decimal Ucret, int OdaNo) {
        Table_1Row rowTable_1Row = ((Table_1Row)(this.NewRow()));
        object[] columnValuesArray = new object[] {
                null,
                AdSoyad,
                TC,
                Mail,
                TelNo,
                GirisTarihi,
                CıkısTarihi,
                Ucret,
                OdaNo};
        rowTable_1Row.ItemArray = columnValuesArray;
        this.Rows.Add(rowTable_1Row);
        return rowTable_1Row;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public Table_1Row FindByMusteriID(int MusteriID) {
        return ((Table_1Row)(this.Rows.Find(new object[] {
                    MusteriID})));
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public override global::System.Data.DataTable Clone() {
        Table_1DataTable cln = ((Table_1DataTable)(base.Clone()));
        cln.InitVars();
        return cln;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected override global::System.Data.DataTable CreateInstance() {
        return new Table_1DataTable();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    internal void InitVars() {
        this.columnMusteriID = base.Columns["MusteriID"];
        this.columnAdSoyad = base.Columns["AdSoyad"];
        this.columnTC = base.Columns["TC"];
        this.columnMail = base.Columns["Mail"];
        this.columnTelNo = base.Columns["TelNo"];
        this.columnGirisTarihi = base.Columns["GirisTarihi"];
        this.columnCıkısTarihi = base.Columns["CıkısTarihi"];
        this.columnUcret = base.Columns["Ucret"];
        this.columnOdaNo = base.Columns["OdaNo"];
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    private void InitClass() {
        this.columnMusteriID = new global::System.Data.DataColumn("MusteriID", typeof(int), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnMusteriID);
        this.columnAdSoyad = new global::System.Data.DataColumn("AdSoyad", typeof(string), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnAdSoyad);
        this.columnTC = new global::System.Data.DataColumn("TC", typeof(int), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnTC);
        this.columnMail = new global::System.Data.DataColumn("Mail", typeof(string), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnMail);
        this.columnTelNo = new global::System.Data.DataColumn("TelNo", typeof(int), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnTelNo);
        this.columnGirisTarihi = new global::System.Data.DataColumn("GirisTarihi", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnGirisTarihi);
        this.columnCıkısTarihi = new global::System.Data.DataColumn("CıkısTarihi", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnCıkısTarihi);
        this.columnUcret = new global::System.Data.DataColumn("Ucret", typeof(decimal), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnUcret);
        this.columnOdaNo = new global::System.Data.DataColumn("OdaNo", typeof(int), null, global::System.Data.MappingType.Element);
        base.Columns.Add(this.columnOdaNo);
        this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                        this.columnMusteriID}, true));
        this.columnMusteriID.AutoIncrement = true;
        this.columnMusteriID.AutoIncrementSeed = -1;
        this.columnMusteriID.AutoIncrementStep = -1;
        this.columnMusteriID.AllowDBNull = false;
        this.columnMusteriID.ReadOnly = true;
        this.columnMusteriID.Unique = true;
        this.columnAdSoyad.AllowDBNull = false;
        this.columnAdSoyad.MaxLength = 50;
        this.columnTC.AllowDBNull = false;
        this.columnMail.AllowDBNull = false;
        this.columnMail.MaxLength = 50;
        this.columnTelNo.AllowDBNull = false;
        this.columnGirisTarihi.AllowDBNull = false;
        this.columnCıkısTarihi.AllowDBNull = false;
        this.columnUcret.AllowDBNull = false;
        this.columnOdaNo.AllowDBNull = false;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public Table_1Row NewTable_1Row() {
        return ((Table_1Row)(this.NewRow()));
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
        return new Table_1Row(builder);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected override global::System.Type GetRowType() {
        return typeof(Table_1Row);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
        base.OnRowChanged(e);
        if ((this.Table_1RowChanged != null)) {
            this.Table_1RowChanged(this, new Table_1RowChangeEvent(((Table_1Row)(e.Row)), e.Action));
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
        base.OnRowChanging(e);
        if ((this.Table_1RowChanging != null)) {
            this.Table_1RowChanging(this, new Table_1RowChangeEvent(((Table_1Row)(e.Row)), e.Action));
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
        base.OnRowDeleted(e);
        if ((this.Table_1RowDeleted != null)) {
            this.Table_1RowDeleted(this, new Table_1RowChangeEvent(((Table_1Row)(e.Row)), e.Action));
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
        base.OnRowDeleting(e);
        if ((this.Table_1RowDeleting != null)) {
            this.Table_1RowDeleting(this, new Table_1RowChangeEvent(((Table_1Row)(e.Row)), e.Action));
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public void RemoveTable_1Row(Table_1Row row) {
        this.Rows.Remove(row);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
        global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
        global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
        ymgDataSet ds = new ymgDataSet();
        global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
        any1.Namespace = "http://www.w3.org/2001/XMLSchema";
        any1.MinOccurs = new decimal(0);
        any1.MaxOccurs = decimal.MaxValue;
        any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
        sequence.Items.Add(any1);
        global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
        any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
        any2.MinOccurs = new decimal(1);
        any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
        sequence.Items.Add(any2);
        global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
        attribute1.Name = "namespace";
        attribute1.FixedValue = ds.Namespace;
        type.Attributes.Add(attribute1);
        global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
        attribute2.Name = "tableTypeName";
        attribute2.FixedValue = "Table_1DataTable";
        type.Attributes.Add(attribute2);
        type.Particle = sequence;
        global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
        if (xs.Contains(dsSchema.TargetNamespace)) {
            global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
            global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
            try {
                global::System.Xml.Schema.XmlSchema schema = null;
                dsSchema.Write(s1);
                for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                    schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                    s2.SetLength(0);
                    schema.Write(s2);
                    if ((s1.Length == s2.Length)) {
                        s1.Position = 0;
                        s2.Position = 0;
                        for (; ((s1.Position != s1.Length) 
                                    && (s1.ReadByte() == s2.ReadByte())); ) {
                            ;
                        }
                        if ((s1.Position == s1.Length)) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if ((s1 != null)) {
                    s1.Close();
                }
                if ((s2 != null)) {
                    s2.Close();
                }
            }
        }
        xs.Add(dsSchema);
        return type;
    }
}

/// <summary>
///Represents strongly named DataRow class.
///</summary>
public partial class Table_1Row : global::System.Data.DataRow {

    private Table_1DataTable tableTable_1;

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    internal Table_1Row(global::System.Data.DataRowBuilder rb) : 
            base(rb) {
        this.tableTable_1 = ((Table_1DataTable)(this.Table));
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public int MusteriID {
        get {
            return ((int)(this[this.tableTable_1.MusteriIDColumn]));
        }
        set {
            this[this.tableTable_1.MusteriIDColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public string AdSoyad {
        get {
            return ((string)(this[this.tableTable_1.AdSoyadColumn]));
        }
        set {
            this[this.tableTable_1.AdSoyadColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public int TC {
        get {
            return ((int)(this[this.tableTable_1.TCColumn]));
        }
        set {
            this[this.tableTable_1.TCColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public string Mail {
        get {
            return ((string)(this[this.tableTable_1.MailColumn]));
        }
        set {
            this[this.tableTable_1.MailColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public int TelNo {
        get {
            return ((int)(this[this.tableTable_1.TelNoColumn]));
        }
        set {
            this[this.tableTable_1.TelNoColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public System.DateTime GirisTarihi {
        get {
            return ((global::System.DateTime)(this[this.tableTable_1.GirisTarihiColumn]));
        }
        set {
            this[this.tableTable_1.GirisTarihiColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public System.DateTime CıkısTarihi {
        get {
            return ((global::System.DateTime)(this[this.tableTable_1.CıkısTarihiColumn]));
        }
        set {
            this[this.tableTable_1.CıkısTarihiColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public decimal Ucret {
        get {
            return ((decimal)(this[this.tableTable_1.UcretColumn]));
        }
        set {
            this[this.tableTable_1.UcretColumn] = value;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public int OdaNo {
        get {
            return ((int)(this[this.tableTable_1.OdaNoColumn]));
        }
        set {
            this[this.tableTable_1.OdaNoColumn] = value;
        }
    }
}

/// <summary>
///Row event argument class
///</summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public class Table_1RowChangeEvent : global::System.EventArgs {

    private Table_1Row eventRow;

    private global::System.Data.DataRowAction eventAction;

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public Table_1RowChangeEvent(Table_1Row row, global::System.Data.DataRowAction action) {
        this.eventRow = row;
        this.eventAction = action;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public Table_1Row Row {
        get {
            return this.eventRow;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public global::System.Data.DataRowAction Action {
        get {
            return this.eventAction;
        }
    }
}
}
}
namespace pansiyonkayit_otomasyonu.ymgDataSetTableAdapters {


/// <summary>
///Represents the connection and commands used to retrieve and save data.
///</summary>
[global::System.ComponentModel.DesignerCategoryAttribute("code")]
[global::System.ComponentModel.ToolboxItem(true)]
[global::System.ComponentModel.DataObjectAttribute(true)]
[global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
", Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
public partial class Table_1TableAdapter : global::System.ComponentModel.Component {

private global::System.Data.SqlClient.SqlDataAdapter _adapter;

private global::System.Data.SqlClient.SqlConnection _connection;

private global::System.Data.SqlClient.SqlTransaction _transaction;

private global::System.Data.SqlClient.SqlCommand[] _commandCollection;

private bool _clearBeforeFill;

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public Table_1TableAdapter() {
    this.ClearBeforeFill = true;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected internal global::System.Data.SqlClient.SqlDataAdapter Adapter {
    get {
        if ((this._adapter == null)) {
            this.InitAdapter();
        }
        return this._adapter;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
internal global::System.Data.SqlClient.SqlConnection Connection {
    get {
        if ((this._connection == null)) {
            this.InitConnection();
        }
        return this._connection;
    }
    set {
        this._connection = value;
        if ((this.Adapter.InsertCommand != null)) {
            this.Adapter.InsertCommand.Connection = value;
        }
        if ((this.Adapter.DeleteCommand != null)) {
            this.Adapter.DeleteCommand.Connection = value;
        }
        if ((this.Adapter.UpdateCommand != null)) {
            this.Adapter.UpdateCommand.Connection = value;
        }
        for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
            if ((this.CommandCollection[i] != null)) {
                ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
            }
        }
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
internal global::System.Data.SqlClient.SqlTransaction Transaction {
    get {
        return this._transaction;
    }
    set {
        this._transaction = value;
        for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
            this.CommandCollection[i].Transaction = this._transaction;
        }
        if (((this.Adapter != null) 
                    && (this.Adapter.DeleteCommand != null))) {
            this.Adapter.DeleteCommand.Transaction = this._transaction;
        }
        if (((this.Adapter != null) 
                    && (this.Adapter.InsertCommand != null))) {
            this.Adapter.InsertCommand.Transaction = this._transaction;
        }
        if (((this.Adapter != null) 
                    && (this.Adapter.UpdateCommand != null))) {
            this.Adapter.UpdateCommand.Transaction = this._transaction;
        }
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
    get {
        if ((this._commandCollection == null)) {
            this.InitCommandCollection();
        }
        return this._commandCollection;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public bool ClearBeforeFill {
    get {
        return this._clearBeforeFill;
    }
    set {
        this._clearBeforeFill = value;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private void InitAdapter() {
    this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
    global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
    tableMapping.SourceTable = "Table";
    tableMapping.DataSetTable = "Table_1";
    tableMapping.ColumnMappings.Add("MusteriID", "MusteriID");
    tableMapping.ColumnMappings.Add("AdSoyad", "AdSoyad");
    tableMapping.ColumnMappings.Add("TC", "TC");
    tableMapping.ColumnMappings.Add("Mail", "Mail");
    tableMapping.ColumnMappings.Add("TelNo", "TelNo");
    tableMapping.ColumnMappings.Add("GirisTarihi", "GirisTarihi");
    tableMapping.ColumnMappings.Add("CıkısTarihi", "CıkısTarihi");
    tableMapping.ColumnMappings.Add("Ucret", "Ucret");
    tableMapping.ColumnMappings.Add("OdaNo", "OdaNo");
    this._adapter.TableMappings.Add(tableMapping);
    this._adapter.DeleteCommand = new global::System.Data.SqlClient.SqlCommand();
    this._adapter.DeleteCommand.Connection = this.Connection;
    this._adapter.DeleteCommand.CommandText = @"DELETE FROM [dbo].[Table_1] WHERE (([MusteriID] = @Original_MusteriID) AND ([AdSoyad] = @Original_AdSoyad) AND ([TC] = @Original_TC) AND ([Mail] = @Original_Mail) AND ([TelNo] = @Original_TelNo) AND ([GirisTarihi] = @Original_GirisTarihi) AND ([CıkısTarihi] = @Original_CıkısTarihi) AND ([Ucret] = @Original_Ucret) AND ([OdaNo] = @Original_OdaNo))";
    this._adapter.DeleteCommand.CommandType = global::System.Data.CommandType.Text;
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_MusteriID", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "MusteriID", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_AdSoyad", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "AdSoyad", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_TC", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TC", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_Mail", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Mail", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_TelNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TelNo", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_GirisTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "GirisTarihi", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_CıkısTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "CıkısTarihi", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_Ucret", global::System.Data.SqlDbType.Money, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Ucret", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_OdaNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "OdaNo", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.InsertCommand = new global::System.Data.SqlClient.SqlCommand();
    this._adapter.InsertCommand.Connection = this.Connection;
    this._adapter.InsertCommand.CommandText = @"INSERT INTO [dbo].[Table_1] ([AdSoyad], [TC], [Mail], [TelNo], [GirisTarihi], [CıkısTarihi], [Ucret], [OdaNo]) VALUES (@AdSoyad, @TC, @Mail, @TelNo, @GirisTarihi, @CıkısTarihi, @Ucret, @OdaNo);
SELECT MusteriID, AdSoyad, TC, Mail, TelNo, GirisTarihi, CıkısTarihi, Ucret, OdaNo FROM Table_1 WHERE (MusteriID = SCOPE_IDENTITY())";
    this._adapter.InsertCommand.CommandType = global::System.Data.CommandType.Text;
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@AdSoyad", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "AdSoyad", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@TC", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TC", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Mail", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Mail", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@TelNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TelNo", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@GirisTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "GirisTarihi", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@CıkısTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "CıkısTarihi", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Ucret", global::System.Data.SqlDbType.Money, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Ucret", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@OdaNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "OdaNo", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand = new global::System.Data.SqlClient.SqlCommand();
    this._adapter.UpdateCommand.Connection = this.Connection;
    this._adapter.UpdateCommand.CommandText = @"UPDATE [dbo].[Table_1] SET [AdSoyad] = @AdSoyad, [TC] = @TC, [Mail] = @Mail, [TelNo] = @TelNo, [GirisTarihi] = @GirisTarihi, [CıkısTarihi] = @CıkısTarihi, [Ucret] = @Ucret, [OdaNo] = @OdaNo WHERE (([MusteriID] = @Original_MusteriID) AND ([AdSoyad] = @Original_AdSoyad) AND ([TC] = @Original_TC) AND ([Mail] = @Original_Mail) AND ([TelNo] = @Original_TelNo) AND ([GirisTarihi] = @Original_GirisTarihi) AND ([CıkısTarihi] = @Original_CıkısTarihi) AND ([Ucret] = @Original_Ucret) AND ([OdaNo] = @Original_OdaNo));
SELECT MusteriID, AdSoyad, TC, Mail, TelNo, GirisTarihi, CıkısTarihi, Ucret, OdaNo FROM Table_1 WHERE (MusteriID = @MusteriID)";
    this._adapter.UpdateCommand.CommandType = global::System.Data.CommandType.Text;
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@AdSoyad", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "AdSoyad", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@TC", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TC", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Mail", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Mail", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@TelNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TelNo", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@GirisTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "GirisTarihi", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@CıkısTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "CıkısTarihi", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Ucret", global::System.Data.SqlDbType.Money, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Ucret", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@OdaNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "OdaNo", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_MusteriID", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "MusteriID", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_AdSoyad", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "AdSoyad", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_TC", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TC", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_Mail", global::System.Data.SqlDbType.NVarChar, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Mail", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_TelNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "TelNo", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_GirisTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "GirisTarihi", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_CıkısTarihi", global::System.Data.SqlDbType.Date, 0, global::System.Data.ParameterDirection.Input, 0, 0, "CıkısTarihi", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_Ucret", global::System.Data.SqlDbType.Money, 0, global::System.Data.ParameterDirection.Input, 0, 0, "Ucret", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@Original_OdaNo", global::System.Data.SqlDbType.Int, 0, global::System.Data.ParameterDirection.Input, 0, 0, "OdaNo", global::System.Data.DataRowVersion.Original, false, null, "", "", ""));
    this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@MusteriID", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 0, 0, "MusteriID", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private void InitConnection() {
    this._connection = new global::System.Data.SqlClient.SqlConnection();
    this._connection.ConnectionString = global::pansiyonkayit_otomasyonu.Properties.Settings.Default.ymgConnectionString;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private void InitCommandCollection() {
    this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
    this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
    this._commandCollection[0].Connection = this.Connection;
    this._commandCollection[0].CommandText = "SELECT MusteriID, AdSoyad, TC, Mail, TelNo, GirisTarihi, CıkısTarihi, Ucret, OdaN" +
        "o FROM dbo.Table_1";
    this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
[global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
public virtual int Fill(ymgDataSet.Table_1DataTable dataTable) {
    this.Adapter.SelectCommand = this.CommandCollection[0];
    if ((this.ClearBeforeFill == true)) {
        dataTable.Clear();
    }
    int returnValue = this.Adapter.Fill(dataTable);
    return returnValue;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
[global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
public virtual ymgDataSet.Table_1DataTable GetData() {
    this.Adapter.SelectCommand = this.CommandCollection[0];
    ymgDataSet.Table_1DataTable dataTable = new ymgDataSet.Table_1DataTable();
    this.Adapter.Fill(dataTable);
    return dataTable;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
public virtual int Update(ymgDataSet.Table_1DataTable dataTable) {
    return this.Adapter.Update(dataTable);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
public virtual int Update(ymgDataSet dataSet) {
    return this.Adapter.Update(dataSet, "Table_1");
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
public virtual int Update(global::System.Data.DataRow dataRow) {
    return this.Adapter.Update(new global::System.Data.DataRow[] {
                dataRow});
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
public virtual int Update(global::System.Data.DataRow[] dataRows) {
    return this.Adapter.Update(dataRows);
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
[global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Delete, true)]
public virtual int Delete(int Original_MusteriID, string Original_AdSoyad, int Original_TC, string Original_Mail, int Original_TelNo, System.DateTime Original_GirisTarihi, System.DateTime Original_CıkısTarihi, decimal Original_Ucret, int Original_OdaNo) {
    this.Adapter.DeleteCommand.Parameters[0].Value = ((int)(Original_MusteriID));
    if ((Original_AdSoyad == null)) {
        throw new global::System.ArgumentNullException("Original_AdSoyad");
    }
    else {
        this.Adapter.DeleteCommand.Parameters[1].Value = ((string)(Original_AdSoyad));
    }
    this.Adapter.DeleteCommand.Parameters[2].Value = ((int)(Original_TC));
    if ((Original_Mail == null)) {
        throw new global::System.ArgumentNullException("Original_Mail");
    }
    else {
        this.Adapter.DeleteCommand.Parameters[3].Value = ((string)(Original_Mail));
    }
    this.Adapter.DeleteCommand.Parameters[4].Value = ((int)(Original_TelNo));
    this.Adapter.DeleteCommand.Parameters[5].Value = ((System.DateTime)(Original_GirisTarihi));
    this.Adapter.DeleteCommand.Parameters[6].Value = ((System.DateTime)(Original_CıkısTarihi));
    this.Adapter.DeleteCommand.Parameters[7].Value = ((decimal)(Original_Ucret));
    this.Adapter.DeleteCommand.Parameters[8].Value = ((int)(Original_OdaNo));
    global::System.Data.ConnectionState previousConnectionState = this.Adapter.DeleteCommand.Connection.State;
    if (((this.Adapter.DeleteCommand.Connection.State & global::System.Data.ConnectionState.Open) 
                != global::System.Data.ConnectionState.Open)) {
        this.Adapter.DeleteCommand.Connection.Open();
    }
    try {
        int returnValue = this.Adapter.DeleteCommand.ExecuteNonQuery();
        return returnValue;
    }
    finally {
        if ((previousConnectionState == global::System.Data.ConnectionState.Closed)) {
            this.Adapter.DeleteCommand.Connection.Close();
        }
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
[global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Insert, true)]
public virtual int Insert(string AdSoyad, int TC, string Mail, int TelNo, System.DateTime GirisTarihi, System.DateTime CıkısTarihi, decimal Ucret, int OdaNo) {
    if ((AdSoyad == null)) {
        throw new global::System.ArgumentNullException("AdSoyad");
    }
    else {
        this.Adapter.InsertCommand.Parameters[0].Value = ((string)(AdSoyad));
    }
    this.Adapter.InsertCommand.Parameters[1].Value = ((int)(TC));
    if ((Mail == null)) {
        throw new global::System.ArgumentNullException("Mail");
    }
    else {
        this.Adapter.InsertCommand.Parameters[2].Value = ((string)(Mail));
    }
    this.Adapter.InsertCommand.Parameters[3].Value = ((int)(TelNo));
    this.Adapter.InsertCommand.Parameters[4].Value = ((System.DateTime)(GirisTarihi));
    this.Adapter.InsertCommand.Parameters[5].Value = ((System.DateTime)(CıkısTarihi));
    this.Adapter.InsertCommand.Parameters[6].Value = ((decimal)(Ucret));
    this.Adapter.InsertCommand.Parameters[7].Value = ((int)(OdaNo));
    global::System.Data.ConnectionState previousConnectionState = this.Adapter.InsertCommand.Connection.State;
    if (((this.Adapter.InsertCommand.Connection.State & global::System.Data.ConnectionState.Open) 
                != global::System.Data.ConnectionState.Open)) {
        this.Adapter.InsertCommand.Connection.Open();
    }
    try {
        int returnValue = this.Adapter.InsertCommand.ExecuteNonQuery();
        return returnValue;
    }
    finally {
        if ((previousConnectionState == global::System.Data.ConnectionState.Closed)) {
            this.Adapter.InsertCommand.Connection.Close();
        }
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
[global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Update, true)]
public virtual int Update(
            string AdSoyad, 
            int TC, 
            string Mail, 
            int TelNo, 
            System.DateTime GirisTarihi, 
            System.DateTime CıkısTarihi, 
            decimal Ucret, 
            int OdaNo, 
            int Original_MusteriID, 
            string Original_AdSoyad, 
            int Original_TC, 
            string Original_Mail, 
            int Original_TelNo, 
            System.DateTime Original_GirisTarihi, 
            System.DateTime Original_CıkısTarihi, 
            decimal Original_Ucret, 
            int Original_OdaNo, 
            int MusteriID) {
    if ((AdSoyad == null)) {
        throw new global::System.ArgumentNullException("AdSoyad");
    }
    else {
        this.Adapter.UpdateCommand.Parameters[0].Value = ((string)(AdSoyad));
    }
    this.Adapter.UpdateCommand.Parameters[1].Value = ((int)(TC));
    if ((Mail == null)) {
        throw new global::System.ArgumentNullException("Mail");
    }
    else {
        this.Adapter.UpdateCommand.Parameters[2].Value = ((string)(Mail));
    }
    this.Adapter.UpdateCommand.Parameters[3].Value = ((int)(TelNo));
    this.Adapter.UpdateCommand.Parameters[4].Value = ((System.DateTime)(GirisTarihi));
    this.Adapter.UpdateCommand.Parameters[5].Value = ((System.DateTime)(CıkısTarihi));
    this.Adapter.UpdateCommand.Parameters[6].Value = ((decimal)(Ucret));
    this.Adapter.UpdateCommand.Parameters[7].Value = ((int)(OdaNo));
    this.Adapter.UpdateCommand.Parameters[8].Value = ((int)(Original_MusteriID));
    if ((Original_AdSoyad == null)) {
        throw new global::System.ArgumentNullException("Original_AdSoyad");
    }
    else {
        this.Adapter.UpdateCommand.Parameters[9].Value = ((string)(Original_AdSoyad));
    }
    this.Adapter.UpdateCommand.Parameters[10].Value = ((int)(Original_TC));
    if ((Original_Mail == null)) {
        throw new global::System.ArgumentNullException("Original_Mail");
    }
    else {
        this.Adapter.UpdateCommand.Parameters[11].Value = ((string)(Original_Mail));
    }
    this.Adapter.UpdateCommand.Parameters[12].Value = ((int)(Original_TelNo));
    this.Adapter.UpdateCommand.Parameters[13].Value = ((System.DateTime)(Original_GirisTarihi));
    this.Adapter.UpdateCommand.Parameters[14].Value = ((System.DateTime)(Original_CıkısTarihi));
    this.Adapter.UpdateCommand.Parameters[15].Value = ((decimal)(Original_Ucret));
    this.Adapter.UpdateCommand.Parameters[16].Value = ((int)(Original_OdaNo));
    this.Adapter.UpdateCommand.Parameters[17].Value = ((int)(MusteriID));
    global::System.Data.ConnectionState previousConnectionState = this.Adapter.UpdateCommand.Connection.State;
    if (((this.Adapter.UpdateCommand.Connection.State & global::System.Data.ConnectionState.Open) 
                != global::System.Data.ConnectionState.Open)) {
        this.Adapter.UpdateCommand.Connection.Open();
    }
    try {
        int returnValue = this.Adapter.UpdateCommand.ExecuteNonQuery();
        return returnValue;
    }
    finally {
        if ((previousConnectionState == global::System.Data.ConnectionState.Closed)) {
            this.Adapter.UpdateCommand.Connection.Close();
        }
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
[global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Update, true)]
public virtual int Update(
            string AdSoyad, 
            int TC, 
            string Mail, 
            int TelNo, 
            System.DateTime GirisTarihi, 
            System.DateTime CıkısTarihi, 
            decimal Ucret, 
            int OdaNo, 
            int Original_MusteriID, 
            string Original_AdSoyad, 
            int Original_TC, 
            string Original_Mail, 
            int Original_TelNo, 
            System.DateTime Original_GirisTarihi, 
            System.DateTime Original_CıkısTarihi, 
            decimal Original_Ucret, 
            int Original_OdaNo) {
    return this.Update(AdSoyad, TC, Mail, TelNo, GirisTarihi, CıkısTarihi, Ucret, OdaNo, Original_MusteriID, Original_AdSoyad, Original_TC, Original_Mail, Original_TelNo, Original_GirisTarihi, Original_CıkısTarihi, Original_Ucret, Original_OdaNo, Original_MusteriID);
}
}

/// <summary>
///TableAdapterManager is used to coordinate TableAdapters in the dataset to enable Hierarchical Update scenarios
///</summary>
[global::System.ComponentModel.DesignerCategoryAttribute("code")]
[global::System.ComponentModel.ToolboxItem(true)]
[global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterManagerDesigner, Microsoft.VSD" +
"esigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapterManager")]
public partial class TableAdapterManager : global::System.ComponentModel.Component {

private UpdateOrderOption _updateOrder;

private Table_1TableAdapter _table_1TableAdapter;

private bool _backupDataSetBeforeUpdate;

private global::System.Data.IDbConnection _connection;

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public UpdateOrderOption UpdateOrder {
    get {
        return this._updateOrder;
    }
    set {
        this._updateOrder = value;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.EditorAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterManagerPropertyEditor, Microso" +
    "ft.VSDesigner, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3" +
    "a", "System.Drawing.Design.UITypeEditor")]
public Table_1TableAdapter Table_1TableAdapter {
    get {
        return this._table_1TableAdapter;
    }
    set {
        this._table_1TableAdapter = value;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public bool BackupDataSetBeforeUpdate {
    get {
        return this._backupDataSetBeforeUpdate;
    }
    set {
        this._backupDataSetBeforeUpdate = value;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Browsable(false)]
public global::System.Data.IDbConnection Connection {
    get {
        if ((this._connection != null)) {
            return this._connection;
        }
        if (((this._table_1TableAdapter != null) 
                    && (this._table_1TableAdapter.Connection != null))) {
            return this._table_1TableAdapter.Connection;
        }
        return null;
    }
    set {
        this._connection = value;
    }
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
[global::System.ComponentModel.Browsable(false)]
public int TableAdapterInstanceCount {
    get {
        int count = 0;
        if ((this._table_1TableAdapter != null)) {
            count = (count + 1);
        }
        return count;
    }
}

/// <summary>
///Update rows in top-down order.
///</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private int UpdateUpdatedRows(ymgDataSet dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
    int result = 0;
    if ((this._table_1TableAdapter != null)) {
        global::System.Data.DataRow[] updatedRows = dataSet.Table_1.Select(null, null, global::System.Data.DataViewRowState.ModifiedCurrent);
        updatedRows = this.GetRealUpdatedRows(updatedRows, allAddedRows);
        if (((updatedRows != null) 
                    && (0 < updatedRows.Length))) {
            result = (result + this._table_1TableAdapter.Update(updatedRows));
            allChangedRows.AddRange(updatedRows);
        }
    }
    return result;
}

/// <summary>
///Insert rows in top-down order.
///</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private int UpdateInsertedRows(ymgDataSet dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
    int result = 0;
    if ((this._table_1TableAdapter != null)) {
        global::System.Data.DataRow[] addedRows = dataSet.Table_1.Select(null, null, global::System.Data.DataViewRowState.Added);
        if (((addedRows != null) 
                    && (0 < addedRows.Length))) {
            result = (result + this._table_1TableAdapter.Update(addedRows));
            allAddedRows.AddRange(addedRows);
        }
    }
    return result;
}

/// <summary>
///Delete rows in bottom-up order.
///</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private int UpdateDeletedRows(ymgDataSet dataSet, global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows) {
    int result = 0;
    if ((this._table_1TableAdapter != null)) {
        global::System.Data.DataRow[] deletedRows = dataSet.Table_1.Select(null, null, global::System.Data.DataViewRowState.Deleted);
        if (((deletedRows != null) 
                    && (0 < deletedRows.Length))) {
            result = (result + this._table_1TableAdapter.Update(deletedRows));
            allChangedRows.AddRange(deletedRows);
        }
    }
    return result;
}

/// <summary>
///Remove inserted rows that become updated rows after calling TableAdapter.Update(inserted rows) first
///</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private global::System.Data.DataRow[] GetRealUpdatedRows(global::System.Data.DataRow[] updatedRows, global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows) {
    if (((updatedRows == null) 
                || (updatedRows.Length < 1))) {
        return updatedRows;
    }
    if (((allAddedRows == null) 
                || (allAddedRows.Count < 1))) {
        return updatedRows;
    }
    global::System.Collections.Generic.List<global::System.Data.DataRow> realUpdatedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
    for (int i = 0; (i < updatedRows.Length); i = (i + 1)) {
        global::System.Data.DataRow row = updatedRows[i];
        if ((allAddedRows.Contains(row) == false)) {
            realUpdatedRows.Add(row);
        }
    }
    return realUpdatedRows.ToArray();
}

/// <summary>
///Update all changes to the dataset.
///</summary>
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public virtual int UpdateAll(ymgDataSet dataSet) {
    if ((dataSet == null)) {
        throw new global::System.ArgumentNullException("dataSet");
    }
    if ((dataSet.HasChanges() == false)) {
        return 0;
    }
    if (((this._table_1TableAdapter != null) 
                && (this.MatchTableAdapterConnection(this._table_1TableAdapter.Connection) == false))) {
        throw new global::System.ArgumentException("TableAdapterManager tarafından yönetilen tüm TableAdapter\'lar aynı bağlantı dizes" +
                "ini kullanmalıdır.");
    }
    global::System.Data.IDbConnection workConnection = this.Connection;
    if ((workConnection == null)) {
        throw new global::System.ApplicationException("TableAdapterManager bağlantı bilgisi içermiyor. TableAdapterManager TableAdapter " +
                "özelliklerinin her birini geçerli bir TableAdapter örneğine ayarlayın.");
    }
    bool workConnOpened = false;
    if (((workConnection.State & global::System.Data.ConnectionState.Broken) 
                == global::System.Data.ConnectionState.Broken)) {
        workConnection.Close();
    }
    if ((workConnection.State == global::System.Data.ConnectionState.Closed)) {
        workConnection.Open();
        workConnOpened = true;
    }
    global::System.Data.IDbTransaction workTransaction = workConnection.BeginTransaction();
    if ((workTransaction == null)) {
        throw new global::System.ApplicationException("İşlem başlatılamıyor. Geçerli veri bağlantısı işlemleri desteklemiyor veya geçerl" +
                "i durum işlemin başlatılmasına izin vermiyor.");
    }
    global::System.Collections.Generic.List<global::System.Data.DataRow> allChangedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
    global::System.Collections.Generic.List<global::System.Data.DataRow> allAddedRows = new global::System.Collections.Generic.List<global::System.Data.DataRow>();
    global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter> adaptersWithAcceptChangesDuringUpdate = new global::System.Collections.Generic.List<global::System.Data.Common.DataAdapter>();
    global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection> revertConnections = new global::System.Collections.Generic.Dictionary<object, global::System.Data.IDbConnection>();
    int result = 0;
    global::System.Data.DataSet backupDataSet = null;
    if (this.BackupDataSetBeforeUpdate) {
        backupDataSet = new global::System.Data.DataSet();
        backupDataSet.Merge(dataSet);
    }
    try {
        // ---- Prepare for update -----------
        //
        if ((this._table_1TableAdapter != null)) {
            revertConnections.Add(this._table_1TableAdapter, this._table_1TableAdapter.Connection);
            this._table_1TableAdapter.Connection = ((global::System.Data.SqlClient.SqlConnection)(workConnection));
            this._table_1TableAdapter.Transaction = ((global::System.Data.SqlClient.SqlTransaction)(workTransaction));
            if (this._table_1TableAdapter.Adapter.AcceptChangesDuringUpdate) {
                this._table_1TableAdapter.Adapter.AcceptChangesDuringUpdate = false;
                adaptersWithAcceptChangesDuringUpdate.Add(this._table_1TableAdapter.Adapter);
            }
        }
        // 
        //---- Perform updates -----------
        //
        if ((this.UpdateOrder == UpdateOrderOption.UpdateInsertDelete)) {
            result = (result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows));
            result = (result + this.UpdateInsertedRows(dataSet, allAddedRows));
        }
        else {
            result = (result + this.UpdateInsertedRows(dataSet, allAddedRows));
            result = (result + this.UpdateUpdatedRows(dataSet, allChangedRows, allAddedRows));
        }
        result = (result + this.UpdateDeletedRows(dataSet, allChangedRows));
        // 
        //---- Commit updates -----------
        //
        workTransaction.Commit();
        if ((0 < allAddedRows.Count)) {
            global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
            allAddedRows.CopyTo(rows);
            for (int i = 0; (i < rows.Length); i = (i + 1)) {
                global::System.Data.DataRow row = rows[i];
                row.AcceptChanges();
            }
        }
        if ((0 < allChangedRows.Count)) {
            global::System.Data.DataRow[] rows = new System.Data.DataRow[allChangedRows.Count];
            allChangedRows.CopyTo(rows);
            for (int i = 0; (i < rows.Length); i = (i + 1)) {
                global::System.Data.DataRow row = rows[i];
                row.AcceptChanges();
            }
        }
    }
    catch (global::System.Exception ex) {
        workTransaction.Rollback();
        // ---- Restore the dataset -----------
        if (this.BackupDataSetBeforeUpdate) {
            global::System.Diagnostics.Debug.Assert((backupDataSet != null));
            dataSet.Clear();
            dataSet.Merge(backupDataSet);
        }
        else {
            if ((0 < allAddedRows.Count)) {
                global::System.Data.DataRow[] rows = new System.Data.DataRow[allAddedRows.Count];
                allAddedRows.CopyTo(rows);
                for (int i = 0; (i < rows.Length); i = (i + 1)) {
                    global::System.Data.DataRow row = rows[i];
                    row.AcceptChanges();
                    row.SetAdded();
                }
            }
        }
        throw ex;
    }
    finally {
        if (workConnOpened) {
            workConnection.Close();
        }
        if ((this._table_1TableAdapter != null)) {
            this._table_1TableAdapter.Connection = ((global::System.Data.SqlClient.SqlConnection)(revertConnections[this._table_1TableAdapter]));
            this._table_1TableAdapter.Transaction = null;
        }
        if ((0 < adaptersWithAcceptChangesDuringUpdate.Count)) {
            global::System.Data.Common.DataAdapter[] adapters = new System.Data.Common.DataAdapter[adaptersWithAcceptChangesDuringUpdate.Count];
            adaptersWithAcceptChangesDuringUpdate.CopyTo(adapters);
            for (int i = 0; (i < adapters.Length); i = (i + 1)) {
                global::System.Data.Common.DataAdapter adapter = adapters[i];
                adapter.AcceptChangesDuringUpdate = true;
            }
        }
    }
    return result;
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected virtual void SortSelfReferenceRows(global::System.Data.DataRow[] rows, global::System.Data.DataRelation relation, bool childFirst) {
    global::System.Array.Sort<global::System.Data.DataRow>(rows, new SelfReferenceComparer(relation, childFirst));
}

[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
protected virtual bool MatchTableAdapterConnection(global::System.Data.IDbConnection inputConnection) {
    if ((this._connection != null)) {
        return true;
    }
    if (((this.Connection == null) 
                || (inputConnection == null))) {
        return true;
    }
    if (string.Equals(this.Connection.ConnectionString, inputConnection.ConnectionString, global::System.StringComparison.Ordinal)) {
        return true;
    }
    return false;
}

/// <summary>
///Update Order Option
///</summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
public enum UpdateOrderOption {

    InsertUpdateDelete = 0,

    UpdateInsertDelete = 1,
}

/// <summary>
///Used to sort self-referenced table's rows
///</summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
private class SelfReferenceComparer : object, global::System.Collections.Generic.IComparer<global::System.Data.DataRow> {

    private global::System.Data.DataRelation _relation;

    private int _childFirst;

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    internal SelfReferenceComparer(global::System.Data.DataRelation relation, bool childFirst) {
        this._relation = relation;
        if (childFirst) {
            this._childFirst = -1;
        }
        else {
            this._childFirst = 1;
        }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    private global::System.Data.DataRow GetRoot(global::System.Data.DataRow row, out int distance) {
        global::System.Diagnostics.Debug.Assert((row != null));
        global::System.Data.DataRow root = row;
        distance = 0;

        global::System.Collections.Generic.IDictionary<global::System.Data.DataRow, global::System.Data.DataRow> traversedRows = new global::System.Collections.Generic.Dictionary<global::System.Data.DataRow, global::System.Data.DataRow>();
        traversedRows[row] = row;

        global::System.Data.DataRow parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
        for (
        ; ((parent != null) 
                    && (traversedRows.ContainsKey(parent) == false)); 
        ) {
            distance = (distance + 1);
            root = parent;
            traversedRows[parent] = parent;
            parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Default);
        }

        if ((distance == 0)) {
            traversedRows.Clear();
            traversedRows[row] = row;
            parent = row.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
            for (
            ; ((parent != null) 
                        && (traversedRows.ContainsKey(parent) == false)); 
            ) {
                distance = (distance + 1);
                root = parent;
                traversedRows[parent] = parent;
                parent = parent.GetParentRow(this._relation, global::System.Data.DataRowVersion.Original);
            }
        }

        return root;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "17.0.0.0")]
    public int Compare(global::System.Data.DataRow row1, global::System.Data.DataRow row2) {
        if (object.ReferenceEquals(row1, row2)) {
            return 0;
        }
        if ((row1 == null)) {
            return -1;
        }
        if ((row2 == null)) {
            return 1;
        }

        int distance1 = 0;
        global::System.Data.DataRow root1 = this.GetRoot(row1, out distance1);

        int distance2 = 0;
        global::System.Data.DataRow root2 = this.GetRoot(row2, out distance2);

        if (object.ReferenceEquals(root1, root2)) {
            return (this._childFirst * distance1.CompareTo(distance2));
        }
        else {
            global::System.Diagnostics.Debug.Assert(((root1.Table != null) 
                            && (root2.Table != null)));
            if ((root1.Table.Rows.IndexOf(root1) < root2.Table.Rows.IndexOf(root2))) {
                return -1;
            }
            else {
                return 1;
            }
        }
    }
}
}
}

#pragma warning restore 1591 */